### PR TITLE
Added Finley the betta fish

### PR DESCRIPTION
**Pull request by kristen-howton**
###Changes that were made
-Added Finley the betta to index.html
-Added dialog button functionality to betta fish

###Steps to test
1. Verify that Finley the betta fish shows up in fish list section
2. Click Finley the betta fish dialog button to verify that the dialog for betta fish appears and has all of the details for betta fish.

### CODE REVIEW

**Comment by BradCowart** [comment]
Looks good

**Review by alexcurnow — APPROVED** [review]
Looks great!

**Comment by kristen-howton** [comment]
###Changes that were made
-Fixed conflicts with master
-Added Finley the betta to index.html
-Added dialog button functionality to betta fish

###Steps to test

1. Make sure I did not break master
2. Verify that Finley the betta fish shows up in fish list section
3. Click Finley the betta fish dialog button to verify that the dialog for betta fish appears and has all of the details for betta fish.

**Comment by Bltatum** [comment]
works great!!

**Pull request merged**
